In [ ]:

import os

pasta = "/content"

for arquivo in sorted(os.listdir(pasta)):
    caminho = os.path.join(pasta, arquivo)
    if os.path.isfile(caminho):
        tamanho_mb = os.path.getsize(caminho) / (1024 ** 2)
        print(f"{arquivo} — {tamanho_mb:.2f} MB")

DENGBR23.csv.zip — 37.67 MB
DENGBR24.csv.zip — 178.59 MB
DENGBR25.csv.zip — 39.72 MB

In [ ]:

import zipfile
import os

arquivos_zip = [
    "/content/DENGBR23.csv.zip",
    "/content/DENGBR24.csv.zip",
    "/content/DENGBR25.csv.zip"
]

for caminho in arquivos_zip:
    print(f"\nArquivo: {os.path.basename(caminho)}")
    with zipfile.ZipFile(caminho, "r") as zip_ref:
        for item in zip_ref.infolist():
            print(f"  Nome interno: {item.filename}")
            print(f"  Tamanho descompactado: {item.file_size / (1024**2):.2f} MB")

Arquivo: DENGBR23.csv.zip
  Nome interno: DENGBR23.csv
  Tamanho descompactado: 442.20 MB

Arquivo: DENGBR24.csv.zip
  Nome interno: DENGBR24.csv
  Tamanho descompactado: 1755.14 MB

Arquivo: DENGBR25.csv.zip
  Nome interno: DENGBR25.csv
  Tamanho descompactado: 435.65 MB

In [ ]:

import zipfile
import pandas as pd

arquivos_zip = [
    "/content/DENGBR23.csv.zip",
    "/content/DENGBR24.csv.zip",
    "/content/DENGBR25.csv.zip"
]

for caminho in arquivos_zip:
    with zipfile.ZipFile(caminho, "r") as arquivo_zip:
        nome_csv = arquivo_zip.namelist()[0]

        with arquivo_zip.open(nome_csv) as arquivo_csv:
            cabecalho = pd.read_csv(
                arquivo_csv,
                sep=";",
                encoding="latin1",
                nrows=0
            )

    print(f"\n{'=' * 60}")
    print(f"Arquivo: {nome_csv}")
    print(f"Quantidade de colunas: {len(cabecalho.columns)}")
    print("Colunas:")
    print(cabecalho.columns.tolist())

============================================================
Arquivo: DENGBR23.csv
Quantidade de colunas: 1
Colunas:
['TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,DT_SIN_PRI,SEM_PRI,ANO_NASC,NU_IDADE_N,CS_SEXO,CS_GESTANT,CS_RACA,CS_ESCOL_N,SG_UF,ID_MN_RESI,ID_RG_RESI,ID_PAIS,DT_INVEST,ID_OCUPA_N,FEBRE,MIALGIA,CEFALEIA,EXANTEMA,VOMITO,NAUSEA,DOR_COSTAS,CONJUNTVIT,ARTRITE,ARTRALGIA,PETEQUIA_N,LEUCOPENIA,LACO,DOR_RETRO,DIABETES,HEMATOLOG,HEPATOPAT,RENAL,HIPERTENSA,ACIDO_PEPT,AUTO_IMUNE,DT_CHIK_S1,DT_CHIK_S2,DT_PRNT,RES_CHIKS1,RES_CHIKS2,RESUL_PRNT,DT_SORO,RESUL_SORO,DT_NS1,RESUL_NS1,DT_VIRAL,RESUL_VI_N,DT_PCR,RESUL_PCR_,SOROTIPO,HISTOPA_N,IMUNOH_N,HOSPITALIZ,DT_INTERNA,UF,MUNICIPIO,TPAUTOCTO,COUFINF,COPAISINF,COMUNINF,CLASSI_FIN,CRITERIO,DOENCA_TRA,CLINC_CHIK,EVOLUCAO,DT_OBITO,DT_ENCERRA,ALRM_HIPOT,ALRM_PLAQ,ALRM_VOM,ALRM_SANG,ALRM_HEMAT,ALRM_ABDOM,ALRM_LETAR,ALRM_HEPAT,ALRM_LIQ,DT_ALRM,GRAV_PULSO,GRAV_CONV,GRAV_ENCH,GRAV_INSUF,GRAV_TAQUI,GRAV_EXTRE,GRAV_HIPOT,GRAV_HEMAT,GRAV_MELEN,GRAV_METRO,GRAV_SANG,GRAV_AST,GRAV_MIOC,GRAV_CONSC,GRAV_ORGAO,DT_GRAV,MANI_HEMOR,EPISTAXE,GENGIVO,METRO,PETEQUIAS,HEMATURA,SANGRAM,LACO_N,PLASMATICO,EVIDENCIA,PLAQ_MENOR,CON_FHD,COMPLICA,TP_SISTEMA,NDUPLIC_N,DT_DIGITA,CS_FLXRET,FLXRECEBI,MIGRADO_W']

============================================================
Arquivo: DENGBR24.csv
Quantidade de colunas: 1
Colunas:
['TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,DT_SIN_PRI,SEM_PRI,ANO_NASC,NU_IDADE_N,CS_SEXO,CS_GESTANT,CS_RACA,CS_ESCOL_N,SG_UF,ID_MN_RESI,ID_RG_RESI,ID_PAIS,DT_INVEST,ID_OCUPA_N,FEBRE,MIALGIA,CEFALEIA,EXANTEMA,VOMITO,NAUSEA,DOR_COSTAS,CONJUNTVIT,ARTRITE,ARTRALGIA,PETEQUIA_N,LEUCOPENIA,LACO,DOR_RETRO,DIABETES,HEMATOLOG,HEPATOPAT,RENAL,HIPERTENSA,ACIDO_PEPT,AUTO_IMUNE,DT_CHIK_S1,DT_CHIK_S2,DT_PRNT,RES_CHIKS1,RES_CHIKS2,RESUL_PRNT,DT_SORO,RESUL_SORO,DT_NS1,RESUL_NS1,DT_VIRAL,RESUL_VI_N,DT_PCR,RESUL_PCR_,SOROTIPO,HISTOPA_N,IMUNOH_N,HOSPITALIZ,DT_INTERNA,UF,MUNICIPIO,TPAUTOCTO,COUFINF,COPAISINF,COMUNINF,CLASSI_FIN,CRITERIO,DOENCA_TRA,CLINC_CHIK,EVOLUCAO,DT_OBITO,DT_ENCERRA,ALRM_HIPOT,ALRM_PLAQ,ALRM_VOM,ALRM_SANG,ALRM_HEMAT,ALRM_ABDOM,ALRM_LETAR,ALRM_HEPAT,ALRM_LIQ,DT_ALRM,GRAV_PULSO,GRAV_CONV,GRAV_ENCH,GRAV_INSUF,GRAV_TAQUI,GRAV_EXTRE,GRAV_HIPOT,GRAV_HEMAT,GRAV_MELEN,GRAV_METRO,GRAV_SANG,GRAV_AST,GRAV_MIOC,GRAV_CONSC,GRAV_ORGAO,DT_GRAV,MANI_HEMOR,EPISTAXE,GENGIVO,METRO,PETEQUIAS,HEMATURA,SANGRAM,LACO_N,PLASMATICO,EVIDENCIA,PLAQ_MENOR,CON_FHD,COMPLICA,TP_SISTEMA,NDUPLIC_N,DT_DIGITA,CS_FLXRET,FLXRECEBI,MIGRADO_W']

============================================================
Arquivo: DENGBR25.csv
Quantidade de colunas: 1
Colunas:
['TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,DT_SIN_PRI,SEM_PRI,ANO_NASC,NU_IDADE_N,CS_SEXO,CS_GESTANT,CS_RACA,CS_ESCOL_N,SG_UF,ID_MN_RESI,ID_RG_RESI,ID_PAIS,DT_INVEST,ID_OCUPA_N,FEBRE,MIALGIA,CEFALEIA,EXANTEMA,VOMITO,NAUSEA,DOR_COSTAS,CONJUNTVIT,ARTRITE,ARTRALGIA,PETEQUIA_N,LEUCOPENIA,LACO,DOR_RETRO,DIABETES,HEMATOLOG,HEPATOPAT,RENAL,HIPERTENSA,ACIDO_PEPT,AUTO_IMUNE,DT_CHIK_S1,DT_CHIK_S2,DT_PRNT,RES_CHIKS1,RES_CHIKS2,RESUL_PRNT,DT_SORO,RESUL_SORO,DT_NS1,RESUL_NS1,DT_VIRAL,RESUL_VI_N,DT_PCR,RESUL_PCR_,SOROTIPO,HISTOPA_N,IMUNOH_N,HOSPITALIZ,DT_INTERNA,UF,MUNICIPIO,TPAUTOCTO,COUFINF,COPAISINF,COMUNINF,CLASSI_FIN,CRITERIO,DOENCA_TRA,CLINC_CHIK,EVOLUCAO,DT_OBITO,DT_ENCERRA,ALRM_HIPOT,ALRM_PLAQ,ALRM_VOM,ALRM_SANG,ALRM_HEMAT,ALRM_ABDOM,ALRM_LETAR,ALRM_HEPAT,ALRM_LIQ,DT_ALRM,GRAV_PULSO,GRAV_CONV,GRAV_ENCH,GRAV_INSUF,GRAV_TAQUI,GRAV_EXTRE,GRAV_HIPOT,GRAV_HEMAT,GRAV_MELEN,GRAV_METRO,GRAV_SANG,GRAV_AST,GRAV_MIOC,GRAV_CONSC,GRAV_ORGAO,DT_GRAV,MANI_HEMOR,EPISTAXE,GENGIVO,METRO,PETEQUIAS,HEMATURA,SANGRAM,LACO_N,PLASMATICO,EVIDENCIA,PLAQ_MENOR,CON_FHD,COMPLICA,TP_SISTEMA,NDUPLIC_N,DT_DIGITA,CS_FLXRET,FLXRECEBI,MIGRADO_W']

In [ ]:

import zipfile
import pandas as pd
import os

arquivos_zip = [
    "/content/DENGBR23.csv.zip",
    "/content/DENGBR24.csv.zip",
    "/content/DENGBR25.csv.zip"
]

for caminho in arquivos_zip:
    with zipfile.ZipFile(caminho, "r") as arquivo_zip:
        nome_csv = arquivo_zip.namelist()[0]

        with arquivo_zip.open(nome_csv) as arquivo_csv:
            cabecalho = pd.read_csv(
                arquivo_csv,
                sep=",",
                encoding="latin1",
                nrows=0
            )

    print(f"\nArquivo: {os.path.basename(caminho)}")
    print(f"Quantidade de colunas: {len(cabecalho.columns)}")
    print(cabecalho.columns.tolist())

Arquivo: DENGBR23.csv.zip
Quantidade de colunas: 121
['TP_NOT', 'ID_AGRAVO', 'DT_NOTIFIC', 'SEM_NOT', 'NU_ANO', 'SG_UF_NOT', 'ID_MUNICIP', 'ID_REGIONA', 'ID_UNIDADE', 'DT_SIN_PRI', 'SEM_PRI', 'ANO_NASC', 'NU_IDADE_N', 'CS_SEXO', 'CS_GESTANT', 'CS_RACA', 'CS_ESCOL_N', 'SG_UF', 'ID_MN_RESI', 'ID_RG_RESI', 'ID_PAIS', 'DT_INVEST', 'ID_OCUPA_N', 'FEBRE', 'MIALGIA', 'CEFALEIA', 'EXANTEMA', 'VOMITO', 'NAUSEA', 'DOR_COSTAS', 'CONJUNTVIT', 'ARTRITE', 'ARTRALGIA', 'PETEQUIA_N', 'LEUCOPENIA', 'LACO', 'DOR_RETRO', 'DIABETES', 'HEMATOLOG', 'HEPATOPAT', 'RENAL', 'HIPERTENSA', 'ACIDO_PEPT', 'AUTO_IMUNE', 'DT_CHIK_S1', 'DT_CHIK_S2', 'DT_PRNT', 'RES_CHIKS1', 'RES_CHIKS2', 'RESUL_PRNT', 'DT_SORO', 'RESUL_SORO', 'DT_NS1', 'RESUL_NS1', 'DT_VIRAL', 'RESUL_VI_N', 'DT_PCR', 'RESUL_PCR_', 'SOROTIPO', 'HISTOPA_N', 'IMUNOH_N', 'HOSPITALIZ', 'DT_INTERNA', 'UF', 'MUNICIPIO', 'TPAUTOCTO', 'COUFINF', 'COPAISINF', 'COMUNINF', 'CLASSI_FIN', 'CRITERIO', 'DOENCA_TRA', 'CLINC_CHIK', 'EVOLUCAO', 'DT_OBITO', 'DT_ENCERRA', 'ALRM_HIPOT', 'ALRM_PLAQ', 'ALRM_VOM', 'ALRM_SANG', 'ALRM_HEMAT', 'ALRM_ABDOM', 'ALRM_LETAR', 'ALRM_HEPAT', 'ALRM_LIQ', 'DT_ALRM', 'GRAV_PULSO', 'GRAV_CONV', 'GRAV_ENCH', 'GRAV_INSUF', 'GRAV_TAQUI', 'GRAV_EXTRE', 'GRAV_HIPOT', 'GRAV_HEMAT', 'GRAV_MELEN', 'GRAV_METRO', 'GRAV_SANG', 'GRAV_AST', 'GRAV_MIOC', 'GRAV_CONSC', 'GRAV_ORGAO', 'DT_GRAV', 'MANI_HEMOR', 'EPISTAXE', 'GENGIVO', 'METRO', 'PETEQUIAS', 'HEMATURA', 'SANGRAM', 'LACO_N', 'PLASMATICO', 'EVIDENCIA', 'PLAQ_MENOR', 'CON_FHD', 'COMPLICA', 'TP_SISTEMA', 'NDUPLIC_N', 'DT_DIGITA', 'CS_FLXRET', 'FLXRECEBI', 'MIGRADO_W']

Arquivo: DENGBR24.csv.zip
Quantidade de colunas: 121
['TP_NOT', 'ID_AGRAVO', 'DT_NOTIFIC', 'SEM_NOT', 'NU_ANO', 'SG_UF_NOT', 'ID_MUNICIP', 'ID_REGIONA', 'ID_UNIDADE', 'DT_SIN_PRI', 'SEM_PRI', 'ANO_NASC', 'NU_IDADE_N', 'CS_SEXO', 'CS_GESTANT', 'CS_RACA', 'CS_ESCOL_N', 'SG_UF', 'ID_MN_RESI', 'ID_RG_RESI', 'ID_PAIS', 'DT_INVEST', 'ID_OCUPA_N', 'FEBRE', 'MIALGIA', 'CEFALEIA', 'EXANTEMA', 'VOMITO', 'NAUSEA', 'DOR_COSTAS', 'CONJUNTVIT', 'ARTRITE', 'ARTRALGIA', 'PETEQUIA_N', 'LEUCOPENIA', 'LACO', 'DOR_RETRO', 'DIABETES', 'HEMATOLOG', 'HEPATOPAT', 'RENAL', 'HIPERTENSA', 'ACIDO_PEPT', 'AUTO_IMUNE', 'DT_CHIK_S1', 'DT_CHIK_S2', 'DT_PRNT', 'RES_CHIKS1', 'RES_CHIKS2', 'RESUL_PRNT', 'DT_SORO', 'RESUL_SORO', 'DT_NS1', 'RESUL_NS1', 'DT_VIRAL', 'RESUL_VI_N', 'DT_PCR', 'RESUL_PCR_', 'SOROTIPO', 'HISTOPA_N', 'IMUNOH_N', 'HOSPITALIZ', 'DT_INTERNA', 'UF', 'MUNICIPIO', 'TPAUTOCTO', 'COUFINF', 'COPAISINF', 'COMUNINF', 'CLASSI_FIN', 'CRITERIO', 'DOENCA_TRA', 'CLINC_CHIK', 'EVOLUCAO', 'DT_OBITO', 'DT_ENCERRA', 'ALRM_HIPOT', 'ALRM_PLAQ', 'ALRM_VOM', 'ALRM_SANG', 'ALRM_HEMAT', 'ALRM_ABDOM', 'ALRM_LETAR', 'ALRM_HEPAT', 'ALRM_LIQ', 'DT_ALRM', 'GRAV_PULSO', 'GRAV_CONV', 'GRAV_ENCH', 'GRAV_INSUF', 'GRAV_TAQUI', 'GRAV_EXTRE', 'GRAV_HIPOT', 'GRAV_HEMAT', 'GRAV_MELEN', 'GRAV_METRO', 'GRAV_SANG', 'GRAV_AST', 'GRAV_MIOC', 'GRAV_CONSC', 'GRAV_ORGAO', 'DT_GRAV', 'MANI_HEMOR', 'EPISTAXE', 'GENGIVO', 'METRO', 'PETEQUIAS', 'HEMATURA', 'SANGRAM', 'LACO_N', 'PLASMATICO', 'EVIDENCIA', 'PLAQ_MENOR', 'CON_FHD', 'COMPLICA', 'TP_SISTEMA', 'NDUPLIC_N', 'DT_DIGITA', 'CS_FLXRET', 'FLXRECEBI', 'MIGRADO_W']

Arquivo: DENGBR25.csv.zip
Quantidade de colunas: 121
['TP_NOT', 'ID_AGRAVO', 'DT_NOTIFIC', 'SEM_NOT', 'NU_ANO', 'SG_UF_NOT', 'ID_MUNICIP', 'ID_REGIONA', 'ID_UNIDADE', 'DT_SIN_PRI', 'SEM_PRI', 'ANO_NASC', 'NU_IDADE_N', 'CS_SEXO', 'CS_GESTANT', 'CS_RACA', 'CS_ESCOL_N', 'SG_UF', 'ID_MN_RESI', 'ID_RG_RESI', 'ID_PAIS', 'DT_INVEST', 'ID_OCUPA_N', 'FEBRE', 'MIALGIA', 'CEFALEIA', 'EXANTEMA', 'VOMITO', 'NAUSEA', 'DOR_COSTAS', 'CONJUNTVIT', 'ARTRITE', 'ARTRALGIA', 'PETEQUIA_N', 'LEUCOPENIA', 'LACO', 'DOR_RETRO', 'DIABETES', 'HEMATOLOG', 'HEPATOPAT', 'RENAL', 'HIPERTENSA', 'ACIDO_PEPT', 'AUTO_IMUNE', 'DT_CHIK_S1', 'DT_CHIK_S2', 'DT_PRNT', 'RES_CHIKS1', 'RES_CHIKS2', 'RESUL_PRNT', 'DT_SORO', 'RESUL_SORO', 'DT_NS1', 'RESUL_NS1', 'DT_VIRAL', 'RESUL_VI_N', 'DT_PCR', 'RESUL_PCR_', 'SOROTIPO', 'HISTOPA_N', 'IMUNOH_N', 'HOSPITALIZ', 'DT_INTERNA', 'UF', 'MUNICIPIO', 'TPAUTOCTO', 'COUFINF', 'COPAISINF', 'COMUNINF', 'CLASSI_FIN', 'CRITERIO', 'DOENCA_TRA', 'CLINC_CHIK', 'EVOLUCAO', 'DT_OBITO', 'DT_ENCERRA', 'ALRM_HIPOT', 'ALRM_PLAQ', 'ALRM_VOM', 'ALRM_SANG', 'ALRM_HEMAT', 'ALRM_ABDOM', 'ALRM_LETAR', 'ALRM_HEPAT', 'ALRM_LIQ', 'DT_ALRM', 'GRAV_PULSO', 'GRAV_CONV', 'GRAV_ENCH', 'GRAV_INSUF', 'GRAV_TAQUI', 'GRAV_EXTRE', 'GRAV_HIPOT', 'GRAV_HEMAT', 'GRAV_MELEN', 'GRAV_METRO', 'GRAV_SANG', 'GRAV_AST', 'GRAV_MIOC', 'GRAV_CONSC', 'GRAV_ORGAO', 'DT_GRAV', 'MANI_HEMOR', 'EPISTAXE', 'GENGIVO', 'METRO', 'PETEQUIAS', 'HEMATURA', 'SANGRAM', 'LACO_N', 'PLASMATICO', 'EVIDENCIA', 'PLAQ_MENOR', 'CON_FHD', 'COMPLICA', 'TP_SISTEMA', 'NDUPLIC_N', 'DT_DIGITA', 'CS_FLXRET', 'FLXRECEBI', 'MIGRADO_W']

In [ ]:

import zipfile
import pandas as pd

caminho = "/content/DENGBR23.csv.zip"

with zipfile.ZipFile(caminho, "r") as arquivo_zip:
    nome_csv = arquivo_zip.namelist()[0]

    with arquivo_zip.open(nome_csv) as arquivo_csv:
        amostra = pd.read_csv(
            arquivo_csv,
            sep=",",
            encoding="latin1",
            nrows=5,
            dtype=str
        )

colunas_interesse = [
    "DT_NOTIFIC",
    "SEM_NOT",
    "SG_UF",
    "ID_MN_RESI",
    "CLASSI_FIN",
    "EVOLUCAO"
]

display(amostra[colunas_interesse])

   DT_NOTIFIC SEM_NOT SG_UF ID_MN_RESI CLASSI_FIN EVOLUCAO
0  2023-01-01  202301    32     320130         10        1
1  2023-01-02  202301    32     320460         10        1
2  2023-01-02  202301    32     320500         10        1
3  2023-01-02  202301    32     320500         10        1
4  2023-01-02  202301    32     320500         10        1

In [ ]:

print("Dimensões da amostra:", amostra.shape)

print("\nCabeçalhos:")
print(amostra.columns.tolist())

print("\nAmostra completa:")
display(amostra.head())

print("\nValores distintos nos campos principais:")
for coluna in ["DT_NOTIFIC", "SEM_NOT", "SG_UF", "ID_MN_RESI",
               "CLASSI_FIN", "EVOLUCAO"]:
    print(f"\n{coluna}:")
    print(amostra[coluna].tolist())

Dimensões da amostra: (5, 121)

Cabeçalhos:
['TP_NOT', 'ID_AGRAVO', 'DT_NOTIFIC', 'SEM_NOT', 'NU_ANO', 'SG_UF_NOT', 'ID_MUNICIP', 'ID_REGIONA', 'ID_UNIDADE', 'DT_SIN_PRI', 'SEM_PRI', 'ANO_NASC', 'NU_IDADE_N', 'CS_SEXO', 'CS_GESTANT', 'CS_RACA', 'CS_ESCOL_N', 'SG_UF', 'ID_MN_RESI', 'ID_RG_RESI', 'ID_PAIS', 'DT_INVEST', 'ID_OCUPA_N', 'FEBRE', 'MIALGIA', 'CEFALEIA', 'EXANTEMA', 'VOMITO', 'NAUSEA', 'DOR_COSTAS', 'CONJUNTVIT', 'ARTRITE', 'ARTRALGIA', 'PETEQUIA_N', 'LEUCOPENIA', 'LACO', 'DOR_RETRO', 'DIABETES', 'HEMATOLOG', 'HEPATOPAT', 'RENAL', 'HIPERTENSA', 'ACIDO_PEPT', 'AUTO_IMUNE', 'DT_CHIK_S1', 'DT_CHIK_S2', 'DT_PRNT', 'RES_CHIKS1', 'RES_CHIKS2', 'RESUL_PRNT', 'DT_SORO', 'RESUL_SORO', 'DT_NS1', 'RESUL_NS1', 'DT_VIRAL', 'RESUL_VI_N', 'DT_PCR', 'RESUL_PCR_', 'SOROTIPO', 'HISTOPA_N', 'IMUNOH_N', 'HOSPITALIZ', 'DT_INTERNA', 'UF', 'MUNICIPIO', 'TPAUTOCTO', 'COUFINF', 'COPAISINF', 'COMUNINF', 'CLASSI_FIN', 'CRITERIO', 'DOENCA_TRA', 'CLINC_CHIK', 'EVOLUCAO', 'DT_OBITO', 'DT_ENCERRA', 'ALRM_HIPOT', 'ALRM_PLAQ', 'ALRM_VOM', 'ALRM_SANG', 'ALRM_HEMAT', 'ALRM_ABDOM', 'ALRM_LETAR', 'ALRM_HEPAT', 'ALRM_LIQ', 'DT_ALRM', 'GRAV_PULSO', 'GRAV_CONV', 'GRAV_ENCH', 'GRAV_INSUF', 'GRAV_TAQUI', 'GRAV_EXTRE', 'GRAV_HIPOT', 'GRAV_HEMAT', 'GRAV_MELEN', 'GRAV_METRO', 'GRAV_SANG', 'GRAV_AST', 'GRAV_MIOC', 'GRAV_CONSC', 'GRAV_ORGAO', 'DT_GRAV', 'MANI_HEMOR', 'EPISTAXE', 'GENGIVO', 'METRO', 'PETEQUIAS', 'HEMATURA', 'SANGRAM', 'LACO_N', 'PLASMATICO', 'EVIDENCIA', 'PLAQ_MENOR', 'CON_FHD', 'COMPLICA', 'TP_SISTEMA', 'NDUPLIC_N', 'DT_DIGITA', 'CS_FLXRET', 'FLXRECEBI', 'MIGRADO_W']

Amostra completa:

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,DT_SIN_PRI,...,EVIDENCIA,PLAQ_MENOR,CON_FHD,COMPLICA,TP_SISTEMA,NDUPLIC_N,DT_DIGITA,CS_FLXRET,FLXRECEBI,MIGRADO_W
0,2,A90,2023-01-01,202301,2023,32,320500,32002,9958762,2023-01-01,...,NaN,NaN,NaN,NaN,NaN,NaN,2023-01-01,NaN,NaN,NaN
1,2,A90,2023-01-02,202301,2023,32,320460,32002,2466066,2023-01-02,...,NaN,NaN,NaN,NaN,NaN,NaN,2023-01-02,NaN,NaN,NaN
2,2,A90,2023-01-02,202301,2023,32,320500,32002,2486016,2023-01-01,...,NaN,NaN,NaN,NaN,NaN,NaN,2023-01-02,NaN,NaN,NaN
3,2,A90,2023-01-02,202301,2023,32,320500,32002,2499436,2023-01-01,...,NaN,NaN,NaN,NaN,NaN,NaN,2023-01-02,NaN,NaN,NaN
4,2,A90,2023-01-02,202301,2023,32,320130,32002,7301413,2023-01-02,...,NaN,NaN,NaN,NaN,NaN,NaN,2023-01-02,NaN,NaN,NaN

Valores distintos nos campos principais:

DT_NOTIFIC:
['2023-01-01', '2023-01-02', '2023-01-02', '2023-01-02', '2023-01-02']

SEM_NOT:
['202301', '202301', '202301', '202301', '202301']

SG_UF:
['32', '32', '32', '32', '32']

ID_MN_RESI:
['320130', '320460', '320500', '320500', '320500']

CLASSI_FIN:
['10', '10', '10', '10', '10']

EVOLUCAO:
['1', '1', '1', '1', '1']

In [ ]:

display(amostra[[
    "DT_NOTIFIC",
    "SEM_NOT",
    "SG_UF",
    "ID_MN_RESI",
    "CLASSI_FIN",
    "EVOLUCAO"
]].head(5))

   DT_NOTIFIC SEM_NOT SG_UF ID_MN_RESI CLASSI_FIN EVOLUCAO
0  2023-01-01  202301    32     320130         10        1
1  2023-01-02  202301    32     320460         10        1
2  2023-01-02  202301    32     320500         10        1
3  2023-01-02  202301    32     320500         10        1
4  2023-01-02  202301    32     320500         10        1

In [ ]:

import zipfile
import pandas as pd

with zipfile.ZipFile("/content/DENGBR23.csv.zip", "r") as z:
    with z.open("DENGBR23.csv") as f:
        classificacoes = pd.read_csv(
            f,
            sep=",",
            encoding="latin1",
            usecols=["CLASSI_FIN"],
            dtype=str
        )

print(classificacoes["CLASSI_FIN"].value_counts(dropna=False).head(15))

CLASSI_FIN
10     1401419
8       207687
11       23668
0         8112
NaN       3384
12        1686
Name: count, dtype: int64

In [ ]:

with zipfile.ZipFile("/content/DENGBR23.csv.zip", "r") as z:
    with z.open("DENGBR23.csv") as f:
        criterios = pd.read_csv(
            f,
            sep=",",
            encoding="latin1",
            usecols=["CRITERIO"],
            dtype=str
        )

print(criterios["CRITERIO"].value_counts(dropna=False))

CRITERIO
2      766131
1      655107
NaN    199484
3       22316
0        2918
Name: count, dtype: int64

In [ ]:

with zipfile.ZipFile("/content/DENGBR23.csv.zip", "r") as z:
    with z.open("DENGBR23.csv") as f:
        resumo = pd.read_csv(
            f,
            sep=",",
            encoding="latin1",
            usecols=["CLASSI_FIN", "CRITERIO"],
            dtype=str
        )

tabela = pd.crosstab(
    resumo["CLASSI_FIN"].fillna("Ausente"),
    resumo["CRITERIO"].fillna("Ausente"),
    margins=True
)

display(tabela)

CRITERIO       0       1       2      3  Ausente      All
CLASSI_FIN
0           2166      26      14   5906        0     8112
10           733  638301  754849   7536        0  1401419
11            17   14451    8624    576        0    23668
12             2    1293     335     56        0     1686
8              0    1032    2304   8015   196336   207687
Ausente        0       4       5    227     3148     3384
All         2918  655107  766131  22316   199484  1645956

In [ ]:

classificacoes_dengue = resumo[
    resumo["CLASSI_FIN"].isin(["10", "11", "12"])
]

print("Registros classificados como dengue:", len(classificacoes_dengue))

print("\nDistribuição por classificação:")
print(classificacoes_dengue["CLASSI_FIN"].value_counts().sort_index())

Registros classificados como dengue: 1426773

Distribuição por classificação:
CLASSI_FIN
10    1401419
11      23668
12       1686
Name: count, dtype: int64

In [ ]:

print("Exemplos de datas de início dos sintomas:")
print(amostra["DT_NOTIFIC"].head().tolist())

with zipfile.ZipFile("/content/DENGBR23.csv.zip", "r") as z:
    with z.open("DENGBR23.csv") as f:
        datas = pd.read_csv(
            f,
            sep=",",
            encoding="latin1",
            usecols=["DT_SIN_PRI"],
            dtype=str,
            nrows=10
        )

print("\nExemplos de DT_SIN_PRI:")
print(datas["DT_SIN_PRI"].tolist())

Exemplos de datas de início dos sintomas:
['2023-01-01', '2023-01-02', '2023-01-02', '2023-01-02', '2023-01-02']

Exemplos de DT_SIN_PRI:
['2023-01-01', '2023-01-02', '2023-01-01', '2023-01-01', '2023-01-02', '2023-01-01', '2023-01-02', '2023-01-01', '2023-01-02', '2023-01-01']

In [ ]:

import zipfile
import pandas as pd

arquivo_zip = "/content/DENGBR23.csv.zip"
colunas = ["DT_SIN_PRI", "CLASSI_FIN", "CRITERIO"]

contagem_mensal = {}

with zipfile.ZipFile(arquivo_zip, "r") as z:
    with z.open("DENGBR23.csv") as f:
        for bloco in pd.read_csv(
            f,
            sep=",",
            encoding="latin1",
            usecols=colunas,
            dtype=str,
            chunksize=100_000
        ):
            filtro = (
                bloco["CLASSI_FIN"].isin(["10", "11", "12"])
                & bloco["CRITERIO"].isin(["1", "2"])
            )

            dados = bloco.loc[filtro, "DT_SIN_PRI"]
            datas = pd.to_datetime(dados, errors="coerce")

            meses = datas.dt.to_period("M").dropna().astype(str)
            contagem_mensal.update(
                meses.value_counts().to_dict()
            )

serie_mensal = (
    pd.Series(contagem_mensal, dtype="int64")
    .groupby(level=0).sum()
    .sort_index()
)

print("Registros por mês de início dos sintomas — 2023:")
display(serie_mensal.rename("Quantidade de registros").to_frame())

Registros por mês de início dos sintomas — 2023:

         Quantidade de registros
2023-01                       13
2023-02                       42
2023-03                      133
2023-04                     9684
2023-05                    20903
2023-06                     4057
2023-07                     1157
2023-08                      761
2023-09                      736
2023-10                      951
2023-11                     1311
2023-12                     2478

In [ ]:

arquivo_zip = "/content/DENGBR24.csv.zip"
contagem_mensal_2024 = {}

with zipfile.ZipFile(arquivo_zip, "r") as z:
    with z.open("DENGBR24.csv") as f:
        for bloco in pd.read_csv(
            f,
            sep=",",
            encoding="latin1",
            usecols=["DT_SIN_PRI", "CLASSI_FIN", "CRITERIO"],
            dtype=str,
            chunksize=100_000
        ):
            filtro = (
                bloco["CLASSI_FIN"].isin(["10", "11", "12"])
                & bloco["CRITERIO"].isin(["1", "2"])
            )

            datas = pd.to_datetime(
                bloco.loc[filtro, "DT_SIN_PRI"],
                errors="coerce"
            )

            meses = datas.dt.to_period("M").dropna().astype(str)
            frequencias = meses.value_counts()

            for mes, quantidade in frequencias.items():
                contagem_mensal_2024[mes] = (
                    contagem_mensal_2024.get(mes, 0) + quantidade
                )

serie_mensal_2024 = pd.Series(
    contagem_mensal_2024, dtype="int64"
).sort_index()

display(
    serie_mensal_2024.rename("Quantidade de registros").to_frame()
)

         Quantidade de registros
2023-12                     4659
2024-01                   358922
2024-02                   945857
2024-03                  1563708
2024-04                  1517395
2024-05                  1047394
2024-06                   278357
2024-07                    80156
2024-08                    37381
2024-09                    27785
2024-10                    26282
2024-11                    36987
2024-12                    49773

In [ ]:

arquivo_zip = "/content/DENGBR25.csv.zip"
contagem_mensal_2025 = {}

with zipfile.ZipFile(arquivo_zip, "r") as z:
    with z.open("DENGBR25.csv") as f:
        for bloco in pd.read_csv(
            f,
            sep=",",
            encoding="latin1",
            usecols=["DT_SIN_PRI", "CLASSI_FIN", "CRITERIO"],
            dtype=str,
            chunksize=100_000
        ):
            filtro = (
                bloco["CLASSI_FIN"].isin(["10", "11", "12"])
                & bloco["CRITERIO"].isin(["1", "2"])
            )

            datas = pd.to_datetime(
                bloco.loc[filtro, "DT_SIN_PRI"],
                errors="coerce"
            )

            frequencias = (
                datas.dt.to_period("M")
                .dropna()
                .astype(str)
                .value_counts()
            )

            for mes, quantidade in frequencias.items():
                contagem_mensal_2025[mes] = (
                    contagem_mensal_2025.get(mes, 0) + quantidade
                )

serie_mensal_2025 = pd.Series(
    contagem_mensal_2025, dtype="int64"
).sort_index()

display(
    serie_mensal_2025.rename("Quantidade de registros").to_frame()
)

         Quantidade de registros
2024-12                     8691
2025-01                   184801
2025-02                   243721
2025-03                   355590
2025-04                   285440
2025-05                   193202
2025-06                    59890
2025-07                    27612
2025-08                    22188
2025-09                    23454
2025-10                    23304
2025-11                    21750
2025-12                    20755
2026-01                     2532

In [ ]:

# Combinar as séries mensais já calculadas
comparacao_mensal = pd.concat(
    [
        serie_mensal.rename("2023"),
        serie_mensal_2024.rename("2024"),
        serie_mensal_2025.rename("2025")
    ],
    axis=1
).fillna(0).astype("int64")

# Mostrar somente os meses de janeiro a dezembro de cada ano
comparacao_mensal = comparacao_mensal.loc[
    comparacao_mensal.index.str.match(r"^\d{4}-\d{2}$")
]

display(comparacao_mensal)

          2023     2024    2025
2023-01     13        0       0
2023-02     42        0       0
2023-03    133        0       0
2023-04   9684        0       0
2023-05  20903        0       0
2023-06   4057        0       0
2023-07   1157        0       0
2023-08    761        0       0
2023-09    736        0       0
2023-10    951        0       0
2023-11   1311        0       0
2023-12   2478     4659       0
2024-01      0   358922       0
2024-02      0   945857       0
2024-03      0  1563708       0
2024-04      0  1517395       0
2024-05      0  1047394       0
2024-06      0   278357       0
2024-07      0    80156       0
2024-08      0    37381       0
2024-09      0    27785       0
2024-10      0    26282       0
2024-11      0    36987       0
2024-12      0    49773    8691
2025-01      0        0  184801
2025-02      0        0  243721
2025-03      0        0  355590
2025-04      0        0  285440
2025-05      0        0  193202
2025-06      0        0   59890
2025-07      0        0   27612
2025-08      0        0   22188
2025-09      0        0   23454
2025-10      0        0   23304
2025-11      0        0   21750
2025-12      0        0   20755
2026-01      0        0    2532

In [ ]:

comparacao_por_mes = pd.DataFrame({
    "Mês": range(1, 13),
    "2023": [serie_mensal.get(f"2023-{mes:02d}", 0) for mes in range(1, 13)],
    "2024": [serie_mensal_2024.get(f"2024-{mes:02d}", 0) for mes in range(1, 13)],
    "2025": [serie_mensal_2025.get(f"2025-{mes:02d}", 0) for mes in range(1, 13)]
})

nomes_meses = [
    "Jan", "Fev", "Mar", "Abr", "Mai", "Jun",
    "Jul", "Ago", "Set", "Out", "Nov", "Dez"
]

comparacao_por_mes["Mês"] = nomes_meses

display(comparacao_por_mes)

    Mês   2023     2024    2025
0   Jan     13   358922  184801
1   Fev     42   945857  243721
2   Mar    133  1563708  355590
3   Abr   9684  1517395  285440
4   Mai  20903  1047394  193202
5   Jun   4057   278357   59890
6   Jul   1157    80156   27612
7   Ago    761    37381   22188
8   Set    736    27785   23454
9   Out    951    26282   23304
10  Nov   1311    36987   21750
11  Dez   2478    49773   20755

In [ ]:

arquivos = {
    "2023": "/content/DENGBR23.csv.zip",
    "2024": "/content/DENGBR24.csv.zip",
    "2025": "/content/DENGBR25.csv.zip"
}

for ano, caminho in arquivos.items():
    total_linhas = 0
    total_filtro = 0

    with zipfile.ZipFile(caminho, "r") as z:
        nome_csv = z.namelist()[0]

        with z.open(nome_csv) as f:
            for bloco in pd.read_csv(
                f,
                sep=",",
                encoding="latin1",
                usecols=["CLASSI_FIN", "CRITERIO"],
                dtype=str,
                chunksize=100_000
            ):
                total_linhas += len(bloco)

                filtro = (
                    bloco["CLASSI_FIN"].isin(["10", "11", "12"])
                    & bloco["CRITERIO"].isin(["1", "2"])
                )

                total_filtro += int(filtro.sum())

    print(
        f"{ano}: {total_linhas:,} linhas no total | "
        f"{total_filtro:,} registros no filtro"
    )

2023: 1,645,956 linhas no total | 1,417,853 registros no filtro
2024: 6,564,924 linhas no total | 5,974,656 registros no filtro
2025: 1,643,215 linhas no total | 1,472,930 registros no filtro

In [ ]:

contagem_mensal_2023_corrigida = {}

with zipfile.ZipFile("/content/DENGBR23.csv.zip", "r") as z:
    with z.open("DENGBR23.csv") as f:
        for bloco in pd.read_csv(
            f,
            sep=",",
            encoding="latin1",
            usecols=["DT_SIN_PRI", "CLASSI_FIN", "CRITERIO"],
            dtype=str,
            chunksize=100_000
        ):
            filtro = (
                bloco["CLASSI_FIN"].isin(["10", "11", "12"])
                & bloco["CRITERIO"].isin(["1", "2"])
            )

            datas = pd.to_datetime(
                bloco.loc[filtro, "DT_SIN_PRI"],
                errors="coerce"
            )

            frequencias = (
                datas.dt.to_period("M")
                .dropna()
                .astype(str)
                .value_counts()
            )

            for mes, quantidade in frequencias.items():
                contagem_mensal_2023_corrigida[mes] = (
                    contagem_mensal_2023_corrigida.get(mes, 0)
                    + int(quantidade)
                )

serie_mensal_2023_corrigida = pd.Series(
    contagem_mensal_2023_corrigida,
    dtype="int64"
).sort_index()

display(
    serie_mensal_2023_corrigida.rename(
        "Quantidade de registros"
    ).to_frame()
)

print(
    "\nTotal de registros contabilizados por mês:",
    int(serie_mensal_2023_corrigida.sum())
)

         Quantidade de registros
2023-01                    68069
2023-02                   134038
2023-03                   302535
2023-04                   364273
2023-05                   260866
2023-06                    89989
2023-07                    37662
2023-08                    22980
2023-09                    19176
2023-10                    21745
2023-11                    34803
2023-12                    61717

Total de registros contabilizados por mês: 1417853

In [ ]:

comparacao_por_mes = pd.DataFrame({
    "Mês": [
        "Jan", "Fev", "Mar", "Abr", "Mai", "Jun",
        "Jul", "Ago", "Set", "Out", "Nov", "Dez"
    ],
    "2023": [
        serie_mensal_2023_corrigida.get(f"2023-{mes:02d}", 0)
        for mes in range(1, 13)
    ],
    "2024": [
        serie_mensal_2024.get(f"2024-{mes:02d}", 0)
        for mes in range(1, 13)
    ],
    "2025": [
        serie_mensal_2025.get(f"2025-{mes:02d}", 0)
        for mes in range(1, 13)
    ]
})

display(comparacao_por_mes)

    Mês    2023     2024    2025
0   Jan   68069   358922  184801
1   Fev  134038   945857  243721
2   Mar  302535  1563708  355590
3   Abr  364273  1517395  285440
4   Mai  260866  1047394  193202
5   Jun   89989   278357   59890
6   Jul   37662    80156   27612
7   Ago   22980    37381   22188
8   Set   19176    27785   23454
9   Out   21745    26282   23304
10  Nov   34803    36987   21750
11  Dez   61717    49773   20755

In [ ]:

print("Soma mensal de 2023:", int(serie_mensal_2023_corrigida.sum()))
print("Total filtrado de 2023:", 1417853)

print("\nSoma mensal de 2024:", int(serie_mensal_2024.sum()))
print("Total filtrado de 2024:", 5974656)

print("\nSoma mensal de 2025:", int(serie_mensal_2025.sum()))
print("Total filtrado de 2025:", 1472930)

Soma mensal de 2023: 1417853
Total filtrado de 2023: 1417853

Soma mensal de 2024: 5974656
Total filtrado de 2024: 5974656

Soma mensal de 2025: 1472930
Total filtrado de 2025: 1472930

In [ ]:

for ano, caminho in arquivos.items():
    contagem_ano_sintomas = {}

    with zipfile.ZipFile(caminho, "r") as z:
        nome_csv = z.namelist()[0]

        with z.open(nome_csv) as f:
            for bloco in pd.read_csv(
                f,
                sep=",",
                encoding="latin1",
                usecols=["DT_SIN_PRI", "CLASSI_FIN", "CRITERIO"],
                dtype=str,
                chunksize=100_000
            ):
                filtro = (
                    bloco["CLASSI_FIN"].isin(["10", "11", "12"])
                    & bloco["CRITERIO"].isin(["1", "2"])
                )

                datas = pd.to_datetime(
                    bloco.loc[filtro, "DT_SIN_PRI"],
                    errors="coerce"
                )

                anos_sintomas = datas.dt.year.dropna().astype(int)
                frequencias = anos_sintomas.value_counts()

                for ano_sintomas, quantidade in frequencias.items():
                    contagem_ano_sintomas[ano_sintomas] = (
                        contagem_ano_sintomas.get(ano_sintomas, 0)
                        + int(quantidade)
                    )

    print(f"\nArquivo {ano}:")
    print(pd.Series(contagem_ano_sintomas).sort_index().to_string())

Arquivo 2023:
2023    1417853

Arquivo 2024:
2023       4659
2024    5969997

Arquivo 2025:
2024       8691
2025    1461707
2026       2532

In [ ]:

for ano, caminho in arquivos.items():
    contagem = {}

    with zipfile.ZipFile(caminho, "r") as z:
        nome_csv = z.namelist()[0]

        with z.open(nome_csv) as f:
            for bloco in pd.read_csv(
                f,
                sep=",",
                encoding="latin1",
                usecols=["NU_ANO", "DT_SIN_PRI", "CLASSI_FIN", "CRITERIO"],
                dtype=str,
                chunksize=100_000
            ):
                filtro = (
                    bloco["CLASSI_FIN"].isin(["10", "11", "12"])
                    & bloco["CRITERIO"].isin(["1", "2"])
                )

                dados = bloco.loc[filtro, ["NU_ANO", "DT_SIN_PRI"]].copy()
                dados["ANO_SINTOMAS"] = pd.to_datetime(
                    dados["DT_SIN_PRI"], errors="coerce"
                ).dt.year.astype("Int64")

                resumo = dados.groupby(
                    ["NU_ANO", "ANO_SINTOMAS"], dropna=False
                ).size()

                for chave, quantidade in resumo.items():
                    contagem[chave] = contagem.get(chave, 0) + int(quantidade)

    print(f"\nArquivo {ano}:")
    tabela = pd.Series(contagem).rename("Registros").rename_axis(
        ["Ano de notificação", "Ano dos sintomas"]
    )
    display(tabela.to_frame())

Arquivo 2023:

                                     Registros
Ano de notificação Ano dos sintomas
2023               2023                1417215
2024               2023                    638

Arquivo 2024:

                                     Registros
Ano de notificação Ano dos sintomas
2023               2023                    212
2024               2023                   4447
                   2024                5969520
2025               2024                    477

Arquivo 2025:

                                     Registros
Ano de notificação Ano dos sintomas
2024               2024                   1929
2025               2024                   6762
                   2025                1458981
2026               2025                   2726
                   2026                   2532

In [ ]:

for ano, caminho in arquivos.items():
    totais = {}

    with zipfile.ZipFile(caminho, "r") as z:
        nome_csv = z.namelist()[0]

        with z.open(nome_csv) as f:
            for bloco in pd.read_csv(
                f,
                sep=",",
                encoding="latin1",
                usecols=["NU_ANO", "CLASSI_FIN", "CRITERIO"],
                dtype=str,
                chunksize=100_000
            ):
                filtro = (
                    bloco["CLASSI_FIN"].isin(["10", "11", "12"])
                    & bloco["CRITERIO"].isin(["1", "2"])
                )

                frequencias = (
                    bloco.loc[filtro, "NU_ANO"]
                    .fillna("Ausente")
                    .value_counts()
                )

                for ano_notificacao, quantidade in frequencias.items():
                    totais[ano_notificacao] = (
                        totais.get(ano_notificacao, 0) + int(quantidade)
                    )

    print(f"\nArquivo {ano} — registros por ano de notificação:")
    display(
        pd.Series(totais, name="Registros")
        .sort_index()
        .to_frame()
    )

Arquivo 2023 — registros por ano de notificação:

      Registros
2023    1417215
2024        638

Arquivo 2024 — registros por ano de notificação:

      Registros
2023        212
2024    5973967
2025        477

Arquivo 2025 — registros por ano de notificação:

      Registros
2024       1929
2025    1465743
2026       5258

In [ ]:

for ano, caminho in arquivos.items():
    contagem = {}

    with zipfile.ZipFile(caminho, "r") as z:
        nome_csv = z.namelist()[0]

        with z.open(nome_csv) as f:
            for bloco in pd.read_csv(
                f,
                sep=",",
                encoding="latin1",
                usecols=["NDUPLIC_N", "CLASSI_FIN", "CRITERIO"],
                dtype=str,
                chunksize=100_000
            ):
                filtro = (
                    bloco["CLASSI_FIN"].isin(["10", "11", "12"])
                    & bloco["CRITERIO"].isin(["1", "2"])
                )

                frequencias = (
                    bloco.loc[filtro, "NDUPLIC_N"]
                    .fillna("Ausente")
                    .value_counts()
                )

                for valor, quantidade in frequencias.items():
                    contagem[valor] = contagem.get(valor, 0) + int(quantidade)

    print(f"\nArquivo {ano}:")
    display(
        pd.Series(contagem, name="Registros")
        .sort_values(ascending=False)
        .to_frame()
    )

Arquivo 2023:

         Registros
Ausente    1415778
1             2042
/               33

Arquivo 2024:

         Registros
Ausente    5825456
0           136059
1            13141

Arquivo 2025:

         Registros
Ausente    1435925
0            32530
1             4475

In [ ]:

for ano, caminho in arquivos.items():
    total_filtrado = 0
    datas_validas = 0
    datas_ausentes_invalidas = 0

    with zipfile.ZipFile(caminho, "r") as z:
        nome_csv = z.namelist()[0]

        with z.open(nome_csv) as f:
            for bloco in pd.read_csv(
                f,
                sep=",",
                encoding="latin1",
                usecols=["DT_SIN_PRI", "CLASSI_FIN", "CRITERIO"],
                dtype=str,
                chunksize=100_000
            ):
                filtro = (
                    bloco["CLASSI_FIN"].isin(["10", "11", "12"])
                    & bloco["CRITERIO"].isin(["1", "2"])
                )

                datas = bloco.loc[filtro, "DT_SIN_PRI"]
                convertidas = pd.to_datetime(datas, errors="coerce")

                total_filtrado += len(datas)
                datas_validas += int(convertidas.notna().sum())
                datas_ausentes_invalidas += int(convertidas.isna().sum())

    print(f"\nArquivo {ano}")
    print(f"Registros filtrados: {total_filtrado:,}")
    print(f"Datas válidas: {datas_validas:,}")
    print(f"Datas ausentes ou inválidas: {datas_ausentes_invalidas:,}")

Arquivo 2023
Registros filtrados: 1,417,853
Datas válidas: 1,417,853
Datas ausentes ou inválidas: 0

Arquivo 2024
Registros filtrados: 5,974,656
Datas válidas: 5,974,656
Datas ausentes ou inválidas: 0

Arquivo 2025
Registros filtrados: 1,472,930
Datas válidas: 1,472,930
Datas ausentes ou inválidas: 0

In [ ]:

for ano, caminho in arquivos.items():
    contagem = {}

    with zipfile.ZipFile(caminho, "r") as z:
        nome_csv = z.namelist()[0]

        with z.open(nome_csv) as f:
            for bloco in pd.read_csv(
                f,
                sep=",",
                encoding="latin1",
                usecols=["TP_NOT", "CLASSI_FIN", "CRITERIO"],
                dtype=str,
                chunksize=100_000
            ):
                filtro = (
                    bloco["CLASSI_FIN"].isin(["10", "11", "12"])
                    & bloco["CRITERIO"].isin(["1", "2"])
                )

                frequencias = (
                    bloco.loc[filtro, "TP_NOT"]
                    .fillna("Ausente")
                    .value_counts()
                )

                for valor, quantidade in frequencias.items():
                    contagem[valor] = contagem.get(valor, 0) + int(quantidade)

    print(f"\nArquivo {ano} — tipo de notificação:")
    display(
        pd.Series(contagem, name="Registros")
        .sort_values(ascending=False)
        .to_frame()
    )

Arquivo 2023 — tipo de notificação:

   Registros
2    1417853

Arquivo 2024 — tipo de notificação:

   Registros
2    5974656

Arquivo 2025 — tipo de notificação:

   Registros
2    1472930

In [ ]:

for ano, caminho in arquivos.items():
    contagem = {}

    with zipfile.ZipFile(caminho, "r") as z:
        nome_csv = z.namelist()[0]

        with z.open(nome_csv) as f:
            for bloco in pd.read_csv(
                f,
                sep=",",
                encoding="latin1",
                usecols=["CLASSI_FIN", "CRITERIO"],
                dtype=str,
                chunksize=100_000
            ):
                filtro = (
                    bloco["CLASSI_FIN"].isin(["10", "11", "12"])
                    & bloco["CRITERIO"].isin(["1", "2"])
                )

                frequencias = bloco.loc[filtro, "CLASSI_FIN"].value_counts()

                for valor, quantidade in frequencias.items():
                    contagem[valor] = contagem.get(valor, 0) + int(quantidade)

    print(f"\nArquivo {ano} — classificação final:")
    display(
        pd.Series(contagem, name="Registros")
        .sort_index()
        .to_frame()
    )

Arquivo 2023 — classificação final:

    Registros
10    1393150
11      23075
12       1628

Arquivo 2024 — classificação final:

    Registros
10    5868206
11      97879
12       8571

Arquivo 2025 — classificação final:

    Registros
10    1436450
11      33875
12       2605

In [ ]:

for ano, caminho in arquivos.items():
    valores = {"ID_AGRAVO": {}, "ID_MUNICIP": {}}

    with zipfile.ZipFile(caminho, "r") as z:
        nome_csv = z.namelist()[0]

        with z.open(nome_csv) as f:
            for bloco in pd.read_csv(
                f,
                sep=",",
                encoding="latin1",
                usecols=[
                    "ID_AGRAVO", "ID_MUNICIP",
                    "CLASSI_FIN", "CRITERIO"
                ],
                dtype=str,
                chunksize=100_000
            ):
                filtro = (
                    bloco["CLASSI_FIN"].isin(["10", "11", "12"])
                    & bloco["CRITERIO"].isin(["1", "2"])
                )
                dados = bloco.loc[filtro]

                for coluna in valores:
                    frequencias = (
                        dados[coluna].fillna("Ausente").value_counts()
                    )
                    for valor, quantidade in frequencias.items():
                        valores[coluna][valor] = (
                            valores[coluna].get(valor, 0) + int(quantidade)
                        )

    print(f"\nArquivo {ano}")
    for coluna, contagem in valores.items():
        print(f"{coluna}: {len(contagem)} valores distintos")
        print(sorted(contagem.items(), key=lambda item: -item[1])[:10])

Arquivo 2023
ID_AGRAVO: 1 valores distintos
[('A90', 1417853)]
ID_MUNICIP: 4211 valores distintos
[('411370', 45191), ('420910', 44943), ('354140', 38811), ('530010', 28732), ('317020', 28097), ('320500', 25163), ('420540', 24270), ('410830', 22436), ('330455', 21769), ('320530', 21531)]

Arquivo 2024
ID_AGRAVO: 1 valores distintos
[('A90', 5974656)]
ID_MUNICIP: 5049 valores distintos
[('355030', 655290), ('310620', 233882), ('530010', 196355), ('350950', 127422), ('330455', 110336), ('354990', 99915), ('420910', 82562), ('311860', 68480), ('351880', 67964), ('420240', 57965)]

Arquivo 2025
ID_AGRAVO: 1 valores distintos
[('A90', 1472930)]
ID_MUNICIP: 4441 valores distintos
[('355030', 71902), ('354980', 61288), ('350950', 49128), ('520870', 33126), ('354140', 31775), ('317020', 27333), ('353070', 25712), ('431490', 24837), ('354340', 22686), ('354890', 20727)]

In [3]:

import zipfile
import pandas as pd
from collections import Counter

arquivos = {
    2023: "/content/DENGBR23.csv.zip",
    2024: "/content/DENGBR24.csv.zip",
    2025: "/content/DENGBR25.csv.zip"
}

contagens = Counter()

for ano_arquivo, caminho in arquivos.items():
    with zipfile.ZipFile(caminho) as z:
        with z.open(z.namelist()[0]) as f:
            for bloco in pd.read_csv(
                f,
                sep=",",
                encoding="latin1",
                usecols=["DT_SIN_PRI", "CLASSI_FIN", "CRITERIO"],
                dtype=str,
                chunksize=100_000
            ):
                filtro = (
                    bloco["CLASSI_FIN"].isin(["10", "11", "12"])
                    & bloco["CRITERIO"].isin(["1", "2"])
                )
                dados = bloco.loc[filtro].copy()
                dados["Data"] = pd.to_datetime(
                    dados["DT_SIN_PRI"], errors="coerce"
                )
                dados = dados.dropna(subset=["Data"])
                dados["Ano_sintomas"] = dados["Data"].dt.year
                dados["Mes"] = dados["Data"].dt.month

                agrupado = dados.groupby(
                    ["Ano_sintomas", "Mes", "CLASSI_FIN"]
                ).size()

                for chave, quantidade in agrupado.items():
                    contagens[chave] += int(quantidade)

base_resumida = pd.DataFrame(
    [
        {
            "Ano": chave[0],
            "Mes": chave[1],
            "Classificacao": chave[2],
            "Quantidade_registros": quantidade
        }
        for chave, quantidade in contagens.items()
    ]
).sort_values(["Ano", "Mes", "Classificacao"])

base_resumida.to_csv(
    "/content/dengue_resumo_mensal.csv",
    index=False,
    encoding="utf-8-sig"
)

display(base_resumida.head(10))
print("\nArquivo criado: dengue_resumo_mensal.csv")
print("Linhas na base resumida:", len(base_resumida))

    Ano  Mes Classificacao  Quantidade_registros
0  2023    1            10                 66859
1  2023    1            11                  1127
2  2023    1            12                    83
3  2023    2            10                131931
4  2023    2            11                  1929
5  2023    2            12                   178
6  2023    3            10                297977
7  2023    3            11                  4247
8  2023    3            12                   311
9  2023    4            10                358359

Arquivo criado: dengue_resumo_mensal.csv
Linhas na base resumida: 111

In [ ]:
import pandas as pd

df = pd.read_csv("/content/dengue_resumo_mensal.csv")

print("Dimensões da base:", df.shape)

print("\nTotal de registros contabilizados por ano:")
print(
    df.groupby("Ano")["Quantidade_registros"]
      .sum()
      .sort_index()
)

print("\nTotal geral:", df["Quantidade_registros"].sum())

print("\nLinhas duplicadas no resumo:", df.duplicated().sum())

Dimensões da base: (111, 4)

Total de registros contabilizados por ano:
Ano
2023    1422512
2024    5978688
2025    1461707
2026       2532
Name: Quantidade_registros, dtype: int64

Total geral: 8865439

Linhas duplicadas no resumo: 0

In [ ]:
import zipfile
import pandas as pd

arquivos = {
    2023: "/content/DENGBR23.csv.zip",
    2024: "/content/DENGBR24.csv.zip",
    2025: "/content/DENGBR25.csv.zip"
}

for ano, caminho in arquivos.items():
    with zipfile.ZipFile(caminho) as z:
        with z.open(z.namelist()[0]) as f:
            colunas = pd.read_csv(
                f,
                sep=",",
                encoding="latin1",
                nrows=0
            ).columns.tolist()

    print(f"\nArquivo {ano}")
    print("Colunas identificadoras disponíveis:")
    print([
        c for c in colunas
        if any(p in c.upper() for p in [
            "NU_NOTIFIC", "NU_IDADE", "DT_NOTIFIC",
            "ID_MUNICIP", "NDUPLIC", "DT_SIN_PRI"
        ])
    ])

Arquivo 2023
Colunas identificadoras disponíveis:
['DT_NOTIFIC', 'ID_MUNICIP', 'DT_SIN_PRI', 'NU_IDADE_N', 'NDUPLIC_N']

Arquivo 2024
Colunas identificadoras disponíveis:
['DT_NOTIFIC', 'ID_MUNICIP', 'DT_SIN_PRI', 'NU_IDADE_N', 'NDUPLIC_N']

Arquivo 2025
Colunas identificadoras disponíveis:
['DT_NOTIFIC', 'ID_MUNICIP', 'DT_SIN_PRI', 'NU_IDADE_N', 'NDUPLIC_N']

In [ ]:
import zipfile
import pandas as pd

arquivos = {
    2023: "/content/DENGBR23.csv.zip",
    2024: "/content/DENGBR24.csv.zip",
    2025: "/content/DENGBR25.csv.zip"
}

for ano, caminho in arquivos.items():
    contagem = {}

    with zipfile.ZipFile(caminho) as z:
        with z.open(z.namelist()[0]) as f:
            for bloco in pd.read_csv(
                f,
                sep=",",
                encoding="latin1",
                usecols=["NDUPLIC_N"],
                dtype=str,
                chunksize=100_000
            ):
                valores = bloco["NDUPLIC_N"].fillna("VAZIO")
                for valor, quantidade in valores.value_counts().items():
                    contagem[valor] = contagem.get(valor, 0) + int(quantidade)

    print(f"\nArquivo {ano}")
    print("Valores mais frequentes de NDUPLIC_N:")
    print(sorted(contagem.items(), key=lambda x: x[1], reverse=True)[:10])

Arquivo 2023
Valores mais frequentes de NDUPLIC_N:
[('VAZIO', 1643679), ('1', 2241), ('/', 36)]

Arquivo 2024
Valores mais frequentes de NDUPLIC_N:
[('VAZIO', 6414581), ('0', 136988), ('1', 13355)]

Arquivo 2025
Valores mais frequentes de NDUPLIC_N:
[('VAZIO', 1604338), ('0', 34252), ('1', 4625)]

In [ ]:
import zipfile
import pandas as pd

arquivos = {
    2023: "/content/DENGBR23.csv.zip",
    2024: "/content/DENGBR24.csv.zip",
    2025: "/content/DENGBR25.csv.zip"
}

for ano, caminho in arquivos.items():
    contagem = {}

    with zipfile.ZipFile(caminho) as z:
        with z.open(z.namelist()[0]) as f:
            for bloco in pd.read_csv(
                f,
                sep=",",
                encoding="latin1",
                usecols=["CLASSI_FIN", "CRITERIO", "NDUPLIC_N"],
                dtype=str,
                chunksize=100_000
            ):
                filtro = (
                    bloco["CLASSI_FIN"].isin(["10", "11", "12"])
                    & bloco["CRITERIO"].isin(["1", "2"])
                )

                valores = bloco.loc[filtro, "NDUPLIC_N"].fillna("VAZIO")

                for valor, quantidade in valores.value_counts().items():
                    contagem[valor] = contagem.get(valor, 0) + int(quantidade)

    print(f"\nArquivo {ano} — registros filtrados")
    print(sorted(contagem.items(), key=lambda x: x[1], reverse=True))

Arquivo 2023 — registros filtrados
[('VAZIO', 1415778), ('1', 2042), ('/', 33)]

Arquivo 2024 — registros filtrados
[('VAZIO', 5825456), ('0', 136059), ('1', 13141)]

Arquivo 2025 — registros filtrados
[('VAZIO', 1435925), ('0', 32530), ('1', 4475)]

In [2]:
import zipfile
import pandas as pd

arquivos = {
    2023: "/content/DENGBR23.csv.zip",
    2024: "/content/DENGBR24.csv.zip",
    2025: "/content/DENGBR25.csv.zip"
}

for ano, caminho in arquivos.items():
    total_filtrado = 0
    marcados_duplicidade = 0

    with zipfile.ZipFile(caminho) as z:
        with z.open(z.namelist()[0]) as f:
            for bloco in pd.read_csv(
                f,
                sep=",",
                encoding="latin1",
                usecols=["CLASSI_FIN", "CRITERIO", "NDUPLIC_N"],
                dtype=str,
                chunksize=100_000
            ):
                filtro = (
                    bloco["CLASSI_FIN"].isin(["10", "11", "12"])
                    & bloco["CRITERIO"].isin(["1", "2"])
                )

                dados = bloco.loc[filtro]
                total_filtrado += len(dados)

                marcados_duplicidade += (
                    dados["NDUPLIC_N"].fillna("").str.strip() == "2"
                ).sum()

    print(f"\nArquivo {ano}")
    print("Total filtrado:", total_filtrado)
    print("Marcados como duplicidade (valor 2):",
          marcados_duplicidade)

Arquivo 2023
Total filtrado: 1417853
Marcados como duplicidade (valor 2): 0

Arquivo 2024
Total filtrado: 5974656
Marcados como duplicidade (valor 2): 0

Arquivo 2025
Total filtrado: 1472930
Marcados como duplicidade (valor 2): 0